#!/bin/bash
set -e

# ========================================================
# Script de Exportação de Dados Salesforce para CSV
# - Exporta Accounts e Contacts em arquivos separados no formato .csv
# - Autor: millena84
# ========================================================

CONFIG_FILE="./11_extract_org_metadata.json"

# 🧪 Verifica se o JSON existe
if [[ ! -f "$CONFIG_FILE" ]]; then
  echo "❌ Arquivo $CONFIG_FILE não encontrado!"
  exit 1
fi

# * Extrai alias da org referencia para o filtro
ORG_ALIAS_CONSULTA=$(node -e "
  try {
    const cfg = require('$CONFIG_FILE');
    if (!cfg.orgAliasRetrieve) throw new Error('orgAliasRetrieve ausente.');
    console.log(cfg.orgAliasRetrieve);
  } catch (e) {
    console.error('❌ Erro ao ler orgAliasRetrieve:', e.message);
    process.exit(1);
  }
")

EXPORT_DIR="./1_metadados"
RAW_FILE="$EXPORT_DIR/_saidaTerminal.txt"
OUTPUT_CSV="$EXPORT_DIR/14_VincParamCustom-CanalFormato.csv"

# Cria diretório se não existir
mkdir -p "$EXPORT_DIR"

echo "Alias da org de consulta: $ORG_ALIAS_CONSULTA"
echo "Arquivo final com resultado: $OUTPUT_CSV"

# * Exporta Contacts associados
echo "🔄 Exportando Vínculos relacionados à parametrização do CustomMetadata ..."
# sf data query \
#   --query "QUERY" \
#   --target-org "$ORG_ALIAS_CONSULTA" >> "$RAW_FILE"
sf data query \
  --query "QUERY"\
  --target-org "$ORG_ALIAS_CONSULTA" >> "$RAW_FILE"

echo "✅ Dados exportados com sucesso em: $RAW_FILE"

# * Converte resultado tabular para CSV
echo "🧪 Convertendo resultado tabulado em CSV..."
{
  echo "CanalTab, FormatoTab"
    # | grep -vE '^\+|\| WW2_Canal_ID__r.Name' \
  grep '|' "$RAW_FILE"\
    | grep -vE '^\+|\| IUJ_Par_Canal_Contato_Lkp__r.IUJ_Nome__c'\
    | awk -F '|' '{ sub(/^[ \t]+/, "", $2); sub(/[ \t]+$/, "", $2); sub(/^[ \t]+/, "", $3); sub(/[ \t]+$/, "", $3); print $2 "," $3 }'
} > "$OUTPUT_CSV"
